/** @type {import('tailwindcss').Config} */
module.exports = {
	content: [
		//
		'./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}',
		'./node_modules/flowbite/**/*.js',
	],
	safelist: [
		'from-red-500',
		'from-orange-500',
		'from-amber-500',
		'from-yellow-500',
		'from-lime-500',
		'from-green-500',
		'from-emerald-500',
		'from-teal-500',
		'from-cyan-500',
		'from-sky-500',
		'from-blue-500',
		'from-indigo-500',
		'from-violet-500',
		'from-purple-500',
		'from-fuchsia-500',
		'from-pink-500',
		'from-rose-500',
		'to-red-500',
		'to-orange-500',
		'to-amber-500',
		'to-yellow-500',
		'to-lime-500',
		'to-green-500',
		'to-emerald-500',
		'to-teal-500',
		'to-cyan-500',
		'to-sky-500',
		'to-blue-500',
		'to-indigo-500',
		'to-violet-500',
		'to-purple-500',
		'to-fuchsia-500',
		'to-pink-500',
		'to-rose-500',
	],
	darkMode: 'class',

	theme: {
		extend: {
			colors: {
				gray: {
					50: '#EEEEEE',
					100: '#E2E2E2',
					200: '#D5D5D5',
					300: '#BCBCBC',
					400: '#8A8A8A',
					500: '#717171',
					600: '#585858',
					700: '#3F3F3F',
					800: '#262626',
					900: '#1F1F1F',
				},
				primary: {
					50: '#FAE1D4',
					100: '##F9D4C0',
					200: '#F8C6AC',
					300: '#F6AB84',
					400: '#F59E70',
					500: '#F4905C',
					600: '#F48348',
					700: '#F37534',
					800: '#F26820',
					900: '#F15A0C',
				},
			},
			fontFamily: {
				sans: [
					'Inter',
					'ui-sans-serif',
					'system-ui',
					'-apple-system',
					'system-ui',
					'Segoe UI',
					'Roboto',
					'Helvetica Neue',
					'Arial',
					'Noto Sans',
					'sans-serif',
					'Apple Color Emoji',
					'Segoe UI Emoji',
					'Segoe UI Symbol',
					'Noto Color Emoji',
				],
				body: [
					'Inter',
					'ui-sans-serif',
					'system-ui',
					'-apple-system',
					'system-ui',
					'Segoe UI',
					'Roboto',
					'Helvetica Neue',
					'Arial',
					'Noto Sans',
					'sans-serif',
					'Apple Color Emoji',
					'Segoe UI Emoji',
					'Segoe UI Symbol',
					'Noto Color Emoji',
				],
				mono: [
					'ui-monospace',
					'SFMono-Regular',
					'Menlo',
					'Monaco',
					'Consolas',
					'Liberation Mono',
					'Courier New',
					'monospace',
				],
			},
			transitionProperty: {
				width: 'width',
			},
			textDecoration: ['active'],
			minWidth: {
				kanban: '28rem',
			},
		},
	},

	safelist: [
		// For Astro one
		'grid',
	],

	plugins: [
		//
		require('flowbite/plugin'),
		require('flowbite-typography'),
		require('tailwind-scrollbar')({ nocompatible: true }),
	],
};
